language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install:
  - gem install bundler

rvm:
  - 2.5.3
  - 2.6.0
  - ruby-head
  - jruby-9.2.5.0
  - jruby-head

matrix:
  include:
    - rvm: 2.6.0
      script:
        - bundle exec rake test:accuracy
        - bundle exec rake test:explore
        - bundle exec rake benchmark:memory

  allow_failures:
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
