language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install:
  - gem install bundler -v=1.16.1

after_success:
  - bundle exec rake test:accuracy
  - bundle exec rake benchmark:memory

rvm:
  - 2.3.7
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
